---
# PostgreSQL specific variables
pg_version: 14
cluster_scope: postgres
cluster_namespace: /db/
patroni_data_dir: /dev/data/patroni
patroni_super_user_name: postgres

postgres_packages:
  - postgresql-{{ pg_version }}
  - postgresql-client-{{ pg_version }}
  - postgresql-contrib
  - python3-pip
  - python3-dev
  - libpq-dev