---
- name: Gather network interface facts from host
  setup:
    gather_subset:
      - '!all'
      - '!min'
      - 'interfaces'
    filter: ansible_default_ipv4*
  register: network_facts
  tags: always

- name: Set main network interface fact
  set_fact:
    main_network_interface: "{{ network_facts.ansible_facts.ansible_default_ipv4.interface }}"
  tags: always

- name: Install HAProxy and Keepalived
  apt:
    name:
      - haproxy
      - keepalived
    state: present

- name: Configure HAProxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart HAProxy



- name: Configure Keepalived
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart Keepalived