---
- name: Updating , Configuring hosts file
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Include common role
      include_role:
        name: common




- name: Configure etcd nodes
  hosts: etcd
  become: yes

  tasks:
    - name: Include etcd role
      include_role:
        name: etcd





- name: Configure PostgreSQL nodes
  hosts: postgres
  become: yes

  tasks:
    - name: Include postgres role
      include_role:
        name: postgres





- name: Configure HAProxy nodes
  hosts: haproxy
  become: yes

  tasks:
    - name: Include haproxy role
      include_role:
        name: haproxy



        
- name: Verify cluster setup
  hosts: all
  become: yes

  tasks:
    - name: Wait for services to stabilize
      pause:
        seconds: 10

    - name: Check etcd health
      command: curl http://{{ ansible_default_ipv4.address }}:2379/health
      register: etcd_health
      changed_when: false
      ignore_errors: true
      when: "'etcd' in group_names"

    - name: Display etcd health
      debug:
        var: etcd_health.stdout_lines
      when: etcd_health is defined  and inventory_hostname in groups['etcd']
      
    - name: Get etcd member list
      command: etcdctl --endpoints=http://{{ ansible_default_ipv4.address }}:2379 member list
      register: etcd_members
      when:  inventory_hostname in groups['etcd']
      changed_when: false
      ignore_errors: true

    - name: Display etcd members
      debug:
        var: etcd_members.stdout_lines
      when: etcd_members is defined and inventory_hostname in groups['etcd']

    - name: Check HAProxy stats page
      command: curl -I http://{{ ansible_default_ipv4.address }}:{{ haproxy_stats_port }} 
      register: haproxy_status
      changed_when: false
      ignore_errors: true
      when: and inventory_hostname in groups['haproxy']

    - name: Display HAProxy status
      debug:
        var: haproxy_status.status
      when: haproxy_status is defined and inventory_hostname in groups['haproxy']




    - name: Get Patroni service status
      systemd:
        name: patroni
      register: patroni_status
      ignore_errors: true
      when: inventory_hostname in groups['postgres']

    - name: Display Patroni service state
      debug:
        msg: "Patroni active: {{ patroni_status.status.ActiveState }}"
      when: inventory_hostname in groups['postgres']


    - name: Check Patronictl list
      command: patronictl -c /etc/patroni.yml list
      register: patroni_list
      changed_when: false
      ignore_errors: true
      when: inventory_hostname in groups['postgres']

    - name: Display PostgreSQL state
      debug:
        msg: "{{ patroni_list.stdout_lines if patroni_list is defined else 'No Patroni list available' }}"
      when: inventory_hostname in groups['postgres'] [0]

    - name: Check your credentials in /etc/patroni/credentials.yml
      debug:
        msg: "Ensure you have the correct credentials in /tmp/patroni-credentials.yml for Patroni API access."
      when: inventory_hostname in groups['postgres'] [0]