---
- name: Add PostgreSQL repository key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Add PostgreSQL repository
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"
    state: present
    filename: pgdg.list

- name: Install PostgreSQL packages
  apt:
    name: "{{ postgres_packages }}"
    state: present
    update_cache: yes

- name: Install Python packages
  pip:
    name:
      - patroni
      - python-etcd
      - psycopg2-binary
    state: present

- name: Stop PostgreSQL service
  service:
    name: postgresql
    state: stopped
    enabled: no

- name: Create symlinks for PostgreSQL binaries (wildcard version)
  command: ln -s /usr/lib/postgresql/*/bin/* /usr/bin/
  ignore_errors: true
  no_log: true
  args:
    warn: false
  


- name: Create Patroni data directory
  file:
    path: "{{ patroni_data_dir }}"
    state: directory
    owner: postgres
    group: postgres
    mode: '0700'


- name: Configure Patroni
  template:
    src: patroni.yml.j2
    dest: /etc/patroni.yml
    owner: postgres
    group: postgres
    mode: '0644'

- name: set random password for patroni users
  set_fact:
    patroni_super_user_pass: "{{ lookup('password', '/dev/null length=16 chars=ascii_letters,digits,hexdigits') }}"
    patroni_repl_user_pass: "{{ lookup('password', '/dev/null length=16 chars=ascii_letters,digits,hexdigits') }}"
  when: patroni_super_user_pass is not defined or patroni_repl_user_pass is not defined


- name: Save Patroni credentials to file (run once)
  copy:
    content: |
      patroni_super_user_pass: {{ patroni_super_user_pass }}
      patroni_repl_user_pass: {{ patroni_repl_user_pass }}
    dest: /tmp/patroni-credentials.yml
    owner: postgres
    group: postgres
    mode: '0600'
  run_once: true
  delegate_to: "{{ groups['postgres'] }}"



- name: Read Patroni credentials file
  slurp:
    src: /tmp/patroni-credentials.yml
  register: patroni_creds_raw
  delegate_to: "{{ groups['postgres'] }}"
  run_once: true

- name: Set Patroni password facts
  set_fact:
    patroni_super_user_pass: "{{ (patroni_creds_raw.content | b64decode | from_yaml).patroni_super_user_pass }}"
    patroni_repl_user_pass: "{{ (patroni_creds_raw.content | b64decode | from_yaml).patroni_repl_user_pass }}"

- name: Configure Patroni service
  template:
    src: patroni.service.j2
    dest: /etc/systemd/system/patroni.service
    owner: root
    group: root
    mode: '0644'

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Enable and start Patroni
  service:
    name: patroni
    state: started
    enabled: yes